genomeDir: data/reference/STARGenome
annotation: data/reference/annotation.gtf
samples: samples.tsv
units: units.tsv

counting:
  isPairedEnd: true

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG

gsea:
  scriptFile: gsea/gsea-cli.sh
  params: "-collapse Collapse -mode Max_probe -norm None -nperm 1000 -scoring_scheme weighted -rpt_label workflow -create_svgs true -include_only_symbols true -make_sets true -plot_top_x 20 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false"
  geneSetDatabases: "ftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v7.1.symbols.gmt"
  chip: "ftp.broadinstitute.org://pub/gsea/annotations_versioned/Human_Symbol_with_Remapping_MSigDB.v7.1.chip"
