$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  genomeDir:
    type: string
  annotation:
    type: string
  samples:
    type: string
  units:
    type: string

  counting:
    type: object
    properties:
      isPairedEnd:
        type: boolean
    required:
      - isPairedEnd

  trimming:
    type: object
    properties:
      skip:
        type: boolean
      adapter:
        type: string
        pattern: "^[ACGT]+$"
    required:
      - skip

  c:
    type: object
    properties:
      scriptFile:
        type: string
      params:
        type: string
      geneSetDatabases:
        type: string
      chip:
        type: string
    required:
      - scriptFile
      - params
      - geneSetDatabases
      - chip

required:
  - genomeDir
  - annotation
  - samples
  - units
  - trimming
  - gsea
